# yaml-language-server: $schema=https://raw.githubusercontent.com/brigadecore/brigade/v2/v2/apiserver/schemas/project.json
apiVersion: brigade.sh/v2-beta
kind: Project
metadata:
  id: brigade-slack-gateway
description: Brigade Slack Gateway built with Brigade 2!
spec:
  eventSubscriptions:
  - source: brigade.sh/github
    qualifiers:
      repo: brigadecore/brigade-slack-gateway
    types:
    - check_run:rerequested
    - check_suite:requested
    - check_suite:rerequested
    - push
  workerTemplate:
    git:
      cloneURL: https://github.com/brigadecore/brigade-slack-gateway.git
    jobPolicies:
      allowPrivileged: true
