apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.monitor.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    {{- include "gateway.monitor.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "gateway.selectorLabels" . | nindent 6 }}
      {{- include "gateway.monitor.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gateway.selectorLabels" . | nindent 8 }}
        {{- include "gateway.monitor.labels" . | nindent 8 }}
      annotations:
        checksum/secret: {{ include (print $.Template.BasePath "/common/secret.yaml") . | sha256sum }}
        checksum/config-secret: {{ include (print $.Template.BasePath "/common/config-secret.yaml") . | sha256sum }}
    spec:
      containers:
      - name: monitor
        image: {{ .Values.monitor.image.repository }}:{{ default .Chart.AppVersion .Values.monitor.image.tag }}
        imagePullPolicy: {{ .Values.monitor.image.pullPolicy }}
        env:
        - name: API_ADDRESS
          value: {{ .Values.brigade.apiAddress }}
        - name: API_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "gateway.fullname" . }}
              key: brigadeAPIToken
        - name: API_IGNORE_CERT_WARNINGS
          value: {{ quote .Values.brigade.apiIgnoreCertWarnings }}
        - name: SLACK_APPS_PATH
          value: /app/config/slack-apps.json
        - name: LIST_EVENTS_INTERVAL
          value: {{ .Values.monitor.listEventsInterval }}
        volumeMounts:
        - name: config
          mountPath: /app/config
          readOnly: true
      volumes:
      - name: config
        secret:
          secretName: {{ include "gateway.fullname" . }}-config
      {{- with .Values.monitor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.monitor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
